name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential netcat-openbsd


      - name: Fix permissions
        run: |
          chmod +x tests/config_tester.sh
          chmod +x tests/request_tester.sh
          chmod +x tests/router_tester.sh

      # Configuration parse tester
      - name: Build config tester
        run: make config_tester

      - name: Run config tests
        run: ./tests/config_tester.sh ./config_tester

      # HTTP tester
      - name: Build request tester
        run: make request_tester

      - name: Run request tests
        run: ./tests/request_tester.sh ./config_tester

      # Router tester
      - name: Build router tester
        run: make router_tester

      - name: Run router tests
        run: ./tests/router_tester.sh ./router_tester

      - name: Build webserv
        run: make re

      - name: Setup tester files
        run: |
          chmod +x cgi_test
          chmod +x tester
          mkdir -p YoupiBanane/nop
          mkdir -p YoupiBanane/Yeah
          touch YoupiBanane/youpi.bad_extension
          touch YoupiBanane/youpi.bla
          touch YoupiBanane/nop/youpi.bad_extension
          touch YoupiBanane/nop/other.pouic
          touch YoupiBanane/Yeah/not_happy.bad_extension

      - name: Start webserv
        run: |
          ./webserv default.conf &
          echo $! > server.pid

      - name: Wait for server
        run: |
          for i in {1..20}; do
            nc -z localhost 1234 && break
            sleep 1
            done
          sleep 3 


      - name: Run tester
        run: printf "\n%.0s" {1..20} | ./tester http://localhost:1234

      - name: Stop server
        if: always()
        run: kill $(cat server.pid)
