name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    # add chmod to test scripts 
    - name: Fix permissions
      run: chmod +x tests/config_tester.sh && chmod +x tests/request_tester.sh && chmod +x tests/router_tester.sh

      # Configuration parse tester
    - name: Build config tester
      run: make config_tester  
    - name: Run config tests
      run: ./tests/config_tester.sh ./config_tester
    #  http tester
    - name: Build request tester
      run: make request_tester  
    - name: Run request tests
      run: ./tests/request_tester.sh ./config_tester
    # router tester
    - name: Build router tester
      run: make router_tester
    - name: Run router tests
      run: ./tests/router_tester.sh ./router_tester
      
    - name: Build webserv
      run: make
